### ISSUE TITLE
Suggestion : Add download notification 

### ISSUE THREAD

**Issue by BlueStarOne** [maniac103/squeezeclient#6]
Hello there!

I've been downloading some songs onto my phone and two things :
When trying to download multiple albums at same time, the app kinda crashed, had to uninstall/reinstall to fix (I don't really remember, that was some times ago)
Second, like in squeezer, a downloading notification saying "3 of 10 songs downloaded" would be really cool cuz right now we don't know when the download is finished, if it didn't worked or else

That's a really good app anyway! 

Best regards

**Comment by maniac103** [comment]
That download notification is already there. Did you deny notification permission by any chance?

**Comment by maniac103** [comment]
For the record, this is how the currently implemented notification looks like if you gave the app notification permissions:

![Screenshot_20241106-080554~2](https://github.com/user-attachments/assets/785289be-6b00-4e18-9a36-2fcdc868ac88)

Everything needed for dealing with notification permission is already implemented, including showing a rationale dialog in case the permission was denied once. I don't think the app can do more by itself.

If you double checked notification permission not being denied, and still don't see it, feel free to reopen, but please include more details. Interesting are the Android version you're using as well as what exactly you mean with 'kinda crashed'. If you get into such situation again, a log taken via `adb logcat` (or a crash report zip) would be useful as well.

**Comment by maniac103** [comment]
The crashing probably happened because the file download failed for some reason; the error handling for that was missing. The commit linked above should fix that by showing a notification informing about the failed tracks and offering a retry.
Please let me know if there's still anything broken regarding download in the next release (1.3); I'll release that one sometime next week.

**Comment by maniac103** [comment]
I've just released version 1.3 with the fix above. I'll get to F-Droid in a few days, depending on their build schedule.
