### ISSUE TITLE
Not working with password protection on the server

### ISSUE THREAD

**Issue by sardaukar** [maniac103/squeezeclient#8]
![Screenshot_20241206-194009](https://github.com/user-attachments/assets/f7b1baf9-ddcc-481b-89ed-bc51c2cd47e7)

**Comment by sardaukar** [comment]
This is with the correct username and password pasted in from a password manager's autofill

**Comment by maniac103** [comment]
Indeed, I can reproduce. It shows I never actually tried this yet :-/
I'll have a look into it.

**Comment by maniac103** [comment]
I'll do a 1.4 with this fix sometime next week.

**Comment by sardaukar** [comment]
Thanks!
