### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [maniac103/squeezeclient#9]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8607386190 The apk is built before the last change is committed. Could you please make sure the apk is built from the tag, or just disable the vcsInfo? See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info. Thanks!

**Comment by maniac103** [comment]
I recreated that tag because I noticed the dependency info exclusion didn't work as I intended. Could it have happened that the bot picked up the first tag and got confused by the second one? If so, can the build be retriggered?

**Comment by linsui** [comment]
It picked the correct tag. 05e05979fb23dac8b92cc65da50c79dbea2aea88 :)

**Comment by maniac103** [comment]
Okay. What's the best way to get out of this? Is it enough to re-do the GH release, using freshly-built APKs (and verifying VCS info is correct), or do I need to create a new tag for the build to pick up? My personal preference would be the former, but I'm not sure whether the tooling allows retriggering the build using the same commit.

**Comment by linsui** [comment]
A new apk is enough. :)

**Comment by maniac103** [comment]
Updated the APK after verifying the textproto file pointing to the correct commit. Please let me know if anything is still off (hopefully not). Thanks :+1:
